### ISSUE TITLE
How will we shrink the array when a doodlebug eats an ant?

### ISSUE THREAD

**Issue by elboboua** [elboboua/162group35project#4]

**Comment by ebenwight** [comment]
Looking at the code structure now I see what you're getting at with this.

currently it seems fine to leave the array at a size larger than the number of ants and to just use that as the limiter for checking if you're in bounds of the array.

I think the proper approach will be to set a dead ant / doodlebug to a nullptr when it dies. Then after the round ends go through and count the number of living bugs, move them to a new array and dump the old array.

I know the instructions say we have to use arrrays for storing the bugs, but there's nothing that says that we can't use a sane choice of container to put them all in while we make the transfer to a new array (like, put a buch of pointers in a vector, delete old array, make new array, and fill from vector.
